root = "."

[build]
  bin = "./tmp/main"
  pre_cmd = ["sqlc generate"]
  cmd = "go build -o ./tmp/main ./cmd/api/"
  delay = 1000
  exclude_dir = ["tmp", "internal/db"]
  exclude_regex = ["_test.go"]
  include_ext = ["go", "sql"]
  log = "build-errors.log"
  stop_on_error = true

[color]
  build = "yellow"
  main = "magenta"
  runner = "green"
  watcher = "cyan"

[misc]
# Delete tmp directory on exit
clean_on_exit = true
