version: "2"

severity:
  default: error

output:
  formats:
    sarif:
      path: golangci-lint.sarif
    text:
      path: stderr
      print-issued-lines: true
      print-linter-name: true
  sort-order:
    - linter
    - severity

linters:
  default: fast
  # https://golangci-lint.run/usage/linters/#enabled-by-default
  enable:
    - goheader
    - revive
    - gosec
  # https://golangci-lint.run/usage/linters/#disabled-by-default
  disable:
    - depguard
    - gomoddirectives
    - tagliatelle
    - testpackage
  settings:
    godox:
      keywords: ['BUG', 'FIXME']
    funlen:
      ignore-comments: true
      # Does not support severity setting
    lll:
      line-length: 120
      tab-width: 2
    dupl:
      # tokens count to trigger issue, 150 by default
      threshold: 200
    goheader:
      values:
        const:
          COMPANY: guimochila
      template: |-
        Copyleft (c) {{ YEAR-2024-2025 }}, {{ COMPANY }}. Happy Coding.

formatters:
  enable:
    - gofmt
    - gofumpt
  settings:
    gofumpt:
      module-path: github.com/guimochila/greenlight

issues:
  new: false
  fix: false
